# Generated by Django 3.2.8 on 2021-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ifile',
            field=models.ImageField(default='', upload_to='assets'),
        ),
    ]
