# Generated by Django 3.2.8 on 2021-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
