# Generated by Django 3.2.8 on 2021-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_review_fid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
