# Generated by Django 3.2.8 on 2021-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_review_anon'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=100)),
                ('ifile', models.ImageField(default='', upload_to='static/assets')),
            ],
        ),
    ]
