# Generated by Django 3.2.8 on 2021-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='onwer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
