# Generated by Django 3.2.8 on 2021-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_complaint_onwer'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('sub', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
    ]
